tivix_test/urls.py
from django.contrib import admin
from django.urls import path

from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.BlogPostList.as_view(), name='home'),
    path('blogs/add/', blog_views.BlogPostCreate.as_view(), name='blog-post-create'),
    path('blogs/<int:pk>/', blog_views.BlogPostUpdate.as_view(), name='blog-post-update'),
    # using <str:slug> to allow unicode slugs.
    path('blogs/<str:slug>/', blog_views.BlogPostDetail.as_view(), name='blog-post-detail'),
]

blog/models.py
from django.db import models
from django.urls import reverse

from blog.utils import generate_slug


# Create your models here.
class TimestampMixin(models.Model):
    """
    A simple abstract model class to serve as a mixin for django models
    that require a timestamp during insertion.
    """
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class BlogPost(TimestampMixin):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, allow_unicode=True)
    description = models.TextField(max_length=1000)
    # keeping it simple. we just need to know who is the author.
    author = models.EmailField()

    def save(self, **kwargs):
        """
        Override django Model save method to
        generate a slug from the title during create.
        """
        created = self.pk is None
        if created and not self.slug:
            self.slug = generate_slug(self.title)
        super(BlogPost, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('blog-post-detail', args=(self.slug,))

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from blog.models import BlogPost
from blog.utils import generate_slug, clean_value, allow_clean_links


class BlogPostForm(forms.ModelForm):
    """
    ModelForm to validate and save BlogPosts.
    """
    def clean_title(self):
        is_add = self.instance.pk is None
        # if a blog already exists with a similar title or
        # with a slug similar to one generated from the title,
        # raise error to notify the user about the same.
        self.slug = generate_slug(self.cleaned_data['title'])
        query = BlogPost.objects.filter(Q(title=self.cleaned_data['title']) | Q(slug=self.slug))
        if is_add:
            # during add.
            if query.count() > 0:
                raise forms.ValidationError(_('Blog with a similar title already exists.'))
        else:
            # during edit.
            if query.exclude(pk=self.instance.pk).count() > 0:
                raise forms.ValidationError(_('Blog with a similar title already exists.'))

        # make sure title is alphanumeric.
        try:
            int(self.cleaned_data['title'])
        except ValueError as e:
            pass
        else:
            raise forms.ValidationError(_('Invalid value.'))

        return clean_value(self.cleaned_data['title'], tags=[])  # remove all HTML tags.

    def clean_description(self):
        # make sure it is alphanumeric.
        try:
            int(self.cleaned_data['description'])
        except ValueError as e:
            pass
        else:
            raise forms.ValidationError(_('Invalid value.'))

        return clean_value(
            self.cleaned_data['description'],
            attrs={
                'a': allow_clean_links,  # allow anchor tags which has no javascripts.
                'abbr': ['title'],
                'acronym': ['title'],
                'pre': []
            }
        )  # remove malicious HTML tags.

    class Meta:
        model = BlogPost
        exclude = ['slug']
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from blog.models import BlogPost
from blog.forms import BlogPostForm


# Create your views here.
class BlogPostList(ListView):
    """
    View to list all blogs.
    """
    model = BlogPost
    template_name = 'blog/blog_post_list.html'
    context_object_name = 'blogs'


class BlogPostCreate(CreateView):
    """
    View to create a new blog post.
    Once created it redirects to blog details page.
    """
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'blog/blog_post_create.html'

    def form_valid(self, form):
        """
        Override form_valid method to assign slug generated from title
        into slug field in the instance so that it can be persisted to DB.

        slug field was excluded from form fields since we do not allow
        it to be edited by user.
        """
        # we have generated slug in the form during validation.
        form.instance.slug = form.slug
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        Method used to render erroneous form back to the user.

        Also flash a message saying an error occurred.
        """
        messages.error(self.request, _("Please correct the errors and submit again."))
        return super().form_invalid(form)

    def get_success_url(self):
        """
        Method to return the URL to redirect to after successful save.

        Perfect place to flash a success message.
        """
        messages.success(self.request, _("Blog post created!"))
        return super().get_success_url()


class BlogPostDetail(DetailView):
    """
    View to display the details about a blog post.

    We use slug to query the blog.
    """
    model = BlogPost
    template_name = 'blog/blog_post_detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    context_object_name = 'blog'


class BlogPostUpdate(UpdateView):
    """
    View to update a blog post.

    We use the primary key to query the blog post in this case.
    """
    model = BlogPost
    form_class = BlogPostForm
    template_name = 'blog/blog_post_update.html'

    def form_invalid(self, form):
        """
        Method used to render erroneous form back to the user.

        Also flash a message saying an error occurred.
        """
        messages.error(self.request, _("Please correct the errors and submit again."))
        return super().form_invalid(form)

    def get_success_url(self):
        """
        Method to return the URL to redirect to after successful save.

        Perfect place to flash a success message.
        """
        messages.success(self.request, _("Blog post saved!"))
        return super().get_success_url()

blog/templates/blog/blog_post_create.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-6">
                {% if object is not None %}
                    <h2>Update Blog - {{ object.title|truncatewords_html:5 }}</h2>
                {% else %}
                    <h2>Create a new blog</h2>
                {% endif %}
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-6 col-sm-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <label for="id_author">Email address</label>
                        {{ form.author }}
                        {% if form.author.errors %}
                            <div class="text-danger">{{ form.author.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_title">Title</label>
                        {{ form.title }}
                        {% if form.title.errors %}
                            <div class="text-danger">{{ form.title.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description</label>
                        {{ form.description }}
                        {% if form.description.errors %}
                            <div class="text-danger">{{ form.description.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="form-group form-check">
                        <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                        <a href="{% url 'home' %}" class="btn btn-outline-secondary btn-lg">&lt;&lt;&nbsp;Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_post_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ blog.title }}
                    </h5>
                    <p class="card-text">
                        {{ blog.description|linebreaksbr }}
                    </p>
                    <p class="card-text">
                        <small class="text-muted created-at-content" data-created_at="{{blog.created_at|date:'c'}}" data-author="{{blog.author}}">
                            By {{ blog.author }} on {{ blog.created_at|date:"D d M Y" }} {{ blog.created_at|time:"h:i a" }}
                        </small>
                    </p>
                    <a href="{% url 'blog-post-update' blog.pk %}" class="btn btn-primary">Update this blog</a>
                    <a href="{% url 'home' %}" class="btn btn-outline-secondary">&lt;&lt;&nbsp;Back to list</a>
                </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'js/moment.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $.each($(".created-at-content"), function(index, elem) {
                var datetime = $(elem).attr("data-created_at");  // must be in ISO8601 format.
                var formatted_datetime = moment(datetime).format("ddd, MMM Do YYYY, hh:mm a");
                $(elem).text("By " + $(elem).attr("data-author") + " on " + formatted_datetime);
            });
        });
    </script>
{% endblock %}

blog/templates/blog/blog_post_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-sm-12">
            {% for blog in blogs %}
              <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'blog-post-detail' blog.slug %}">
                            {{ blog.title }}
                        </a>
                    </h5>
                    <p class="card-text">
                        {{ blog.description|linebreaksbr|truncatewords_html:20 }}
                    </p>
                    <p class="card-text">
                        <small class="text-muted created-at-content" data-created_at="{{blog.created_at|date:'c'}}" data-author="{{blog.author}}">
                            By {{ blog.author }} on {{ blog.created_at|date:"D d M Y" }} {{ blog.created_at|time:"h:i a" }}
                        </small>
                    </p>
                </div>
              </div>
              <hr />
            {% endfor %}
          </div>
        </div>
    </div>
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'js/moment.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $.each($(".created-at-content"), function(index, elem) {
                var datetime = $(elem).attr("data-created_at");  // must be in ISO8601 format.
                var formatted_datetime = moment(datetime).format("ddd, MMM Do YYYY, hh:mm a");
                $(elem).text("By " + $(elem).attr("data-author") + " on " + formatted_datetime);
            });
        });
    </script>
{% endblock %}

blog/templates/blog/blog_post_update.html
{% extends "blog/blog_post_create.html" %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
    {% block head %}{% endblock %}

    <title>Tivix Blog Application {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include "partials/navbar.html" %}
    {% include "partials/messages.html" %}
    {% block content %}{% endblock %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    {% block extra_scripts %}{% endblock %}
  </body>
</html>

templates/partials/messages.html
<div id="messages">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.level_tag }} alert-dismissible fade in">
                {# Allow HTML to be embedded in messages #}
                {% if 'safe' in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Tivix Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-right">
      <li class="nav-item active">
        <a class="btn btn-outline-success" href="{% url 'blog-post-create' %}">Write new blog <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>